// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-vesRf3v6m8N0XAZEVbWECdTsCdW0dAE',
    appId: '1:680014927440:web:bf817e179d905884fea355',
    messagingSenderId: '680014927440',
    projectId: 'aws-prn231-doan',
    authDomain: 'aws-prn231-doan.firebaseapp.com',
    storageBucket: 'aws-prn231-doan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS7UFL0TlXg9MNdOTI91Nhf6AkR9EZOyI',
    appId: '1:680014927440:android:bffd3b254690d75efea355',
    messagingSenderId: '680014927440',
    projectId: 'aws-prn231-doan',
    storageBucket: 'aws-prn231-doan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw1cjurGUoZC6zu6mEwS_yzfCmVMa6WAY',
    appId: '1:680014927440:ios:045a428dad41ce08fea355',
    messagingSenderId: '680014927440',
    projectId: 'aws-prn231-doan',
    storageBucket: 'aws-prn231-doan.appspot.com',
    iosBundleId: 'com.aws.awsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw1cjurGUoZC6zu6mEwS_yzfCmVMa6WAY',
    appId: '1:680014927440:ios:66664960d74fd90bfea355',
    messagingSenderId: '680014927440',
    projectId: 'aws-prn231-doan',
    storageBucket: 'aws-prn231-doan.appspot.com',
    iosBundleId: 'com.aws.awsFlutter.RunnerTests',
  );
}
